encoding: utf-8

title: 设计者笔记
email: jskyzero@outlook.com
description: jskyzero's notes about game designer.
baseurl: ""
url: "https://design.jskyzero.com"
twitter_username: jskyzero
github_username: jskyzero

style: light
listen_for_clients_preferred_style: false
footer: 'Enjoy :)'
git_log: true

nav:
  header_pages:
    - index.md
    - index.github.md
    - index.resume.md
    - index.project.md

home:
  # sort: date (Jekyll default), title, or order.
  # For custom post order, set `order: 10` in a post's front matter.
  categories:
    - name: 动作游戏设计
    - name: 动作游戏分析
    - name: 游戏AI
      sort: title
    - name: 专题报告
    - name: 一期一会
    - name: 游戏开发
      sort: title
    - name: 摘录与杂谈
      sort: title

plugins:
  - jekyll-feed
  - jekyll-mermaid
  - jekyll-seo-tag

mermaid:
  src: '/assets/js/mermaid.min.js'

layouts_dir: _theme/_layouts
includes_dir: _theme/_includes
plugins_dir: _theme/_plugins

sass:
  sass_dir: _theme/_sass

disqus:
  shortname: designer-notes

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

exclude:
  - _posts/日常
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg
