# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ jekyll ]
  pull_request:
    branches: [ jekyll ]

jobs:
  build:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     # node-version: [10.x, 12.x, 14.x]
    #     node-version: [10.21.0]


    steps:
    - uses: actions/checkout@v2
      with:
        ref: jekyll
        fetch-depth: 0
    - name: Run with dest path
      uses: helaili/jekyll-build@v2
      with:
        jekyll_build_options: --future
        target_branch: gh-pages
        target_path: /
        keep_history: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: master
        directory: _book
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}