# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Jekyll

on:
  push:
    branches: [ jekyll ]
  pull_request:
    branches: [ jekyll ]

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     # node-version: [10.x, 12.x, 14.x]
    #     node-version: [10.21.0]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: jekyll
        fetch-depth: 0
    - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '3.3.1' # Not needed with a .ruby-version file
        bundler-cache: true
    # fix git error: 
    #   fatal: unsafe repository ('/github/workspace' is owned by someone else)
    # - name: git config
    #   run: |
    #     git config --global --add safe.directory "$GITHUB_WORKSPACE"
    #     git config --global --list

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    # - uses: actions/cache@v3
    #   with:
    #     path: vendor/bundle
    #     key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
    #     restore-keys: |
    #       ${{ runner.os }}-gems-

    # - name: jekyll build
    #   uses: helaili/jekyll-action@v2
    #   with:
    #     pre_build_commands: |
    #       git config --global --add safe.directory "$GITHUB_WORKSPACE"
    #       git config --global --list
    #     jekyll_build_options: --future
    #     target_branch: gh-pages
    #     keep_history: true
    #     token: ${{ secrets.GITHUB_TOKEN }}

    - name: Jekyll - Builder
      # You may pin to the exact commit or the version.
      # uses: Tyler887/jekyllbuild@c2cc71323952c50eaa324ebca5d9353bff6ac217
      uses: Tyler887/jekyllbuild@1.3
      with:
        # Directory where the source files reside.
        source: # optional, default is ./
        # Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.
        destination: # optional, default is ./_site
        # Publishes posts with a future date. When set to true, the build is made with the --future option which overrides the future option that may be set in a Jekyll configuration file.
        future: # optional
        # The SHA-1 of the git commit for which the build is running. Default to GITHUB_SHA.
        build_revision: # optional, default is ${{ github.sha }}
        # Verbose output
        verbose: # optional, default is true
        # Token to access Pages builds (personal access token or GITHUB_TOKEN)
        token: # optional, default is ${{ github.token }}

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: cd ${{ secrets.PROJECT_PATH }} && git pull
