name: Clarity Gist Sync

on:
  schedule:
    - cron: '0 2 * * *' # 每天北京时间上午 10 点
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Run Script
        env:
          CLARITY_TOKEN: ${{ secrets.CLARITY_TOKEN }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: python scripts/update_gist.py